# Generated by Django 5.2.5 on 2025-08-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_order_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
