# Generated by Django 5.2.5 on 2025-08-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
