# Generated by Django 5.2.5 on 2025-08-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_order_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_cinema_hall',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('movie_session', 'row', 'seat')},
        ),
    ]
